services:
#    core.example:
#        class: CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  core.beta.html_adder:
    class: CoreBundle\Beta\BetaHTMLAdder
  core.beta.listener:
    class: CoreBundle\Beta\BetaListener
    arguments:
      - "@core.beta.html_adder"
      - "2018-06-01"
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: processBeta }