archery:
    resource: "@ArcheryBundle/Resources/config/routing.yml"
    prefix:   /

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

location:
    resource: "@LocationBundle/Resources/config/routing.yml"
    prefix:   /location

tournament:
    resource: "@TournamentBundle/Resources/config/routing.yml"
    prefix:   /tournament
