#app/routing_rest.yml
Rest_User : 
  type : rest
  resource: "@UserBundle/Resources/config/routing_rest.yml"

Rest_Club : 
  type : rest
  resource: "@ArcheryBundle/Resources/config/routing_rest.yml"  