<?php

namespace ArcheryBundle\Repository;

/**
 * ArcherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArcherRepository extends \Doctrine\ORM\EntityRepository
{
}
