tournament_homepage:
    path:     /
    defaults: { _controller: TournamentBundle:Tournament:index }
    
tournament_view:
    path:     /{id}
    defaults: { _controller: TournamentBundle:Tournament:view }    
