<?php

namespace TournamentBundle\Repository;

use TournamentBundle\Entity\Tournament;

/**
 * PelotonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PelotonRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPelotons()
  {
    $query = $this->createQueryBuilder('a')
      // Jointure sur l'attribut image
      ->leftJoin('a.participants', 'p')
      ->addSelect('p')
      ->getQuery()
    ;

    return $query->getResult();
  }
}
