<?php

namespace TournamentBundle\Repository;

/**
 * PelotonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PelotonRepository extends \Doctrine\ORM\EntityRepository
{
}
