<?php

namespace TournamentBundle\Repository;

/**
 * PelotonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PelotonRepository extends \Doctrine\ORM\EntityRepository
{
    public function GetPeletonWithParticipants($peloton)
    {        
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.author = :author')
             ->leftJoin('a.participants', 'p');
        $qb->where('a.id = :peloton')
            ->setParameter('peloton', $peloton->getId());

        return $qb
          ->getQuery()
          ->getResult()
        ;
    }
}
